// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbawzgpwgxlrxcrwxvrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiYXd6Z3B3Z3hscnhjcnd4dnJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDY3OTcsImV4cCI6MjA3MzMyMjc5N30.YET85pVNoOLw85kq4OtYxwyS4KHlr-1RopWn9cIfyXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});